/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AzwcDialog {
    }
    interface AzwcFileManager {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "togglePadding": () => Promise<void>;
    }
}
declare global {
    interface HTMLAzwcDialogElement extends Components.AzwcDialog, HTMLStencilElement {
    }
    var HTMLAzwcDialogElement: {
        prototype: HTMLAzwcDialogElement;
        new (): HTMLAzwcDialogElement;
    };
    interface HTMLAzwcFileManagerElement extends Components.AzwcFileManager, HTMLStencilElement {
    }
    var HTMLAzwcFileManagerElement: {
        prototype: HTMLAzwcFileManagerElement;
        new (): HTMLAzwcFileManagerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "azwc-dialog": HTMLAzwcDialogElement;
        "azwc-file-manager": HTMLAzwcFileManagerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AzwcDialog {
        "onCustomStateChange"?: (event: CustomEvent<any>) => void;
    }
    interface AzwcFileManager {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "azwc-dialog": AzwcDialog;
        "azwc-file-manager": AzwcFileManager;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "azwc-dialog": LocalJSX.AzwcDialog & JSXBase.HTMLAttributes<HTMLAzwcDialogElement>;
            "azwc-file-manager": LocalJSX.AzwcFileManager & JSXBase.HTMLAttributes<HTMLAzwcFileManagerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
